name: momentum_top_x_equal_weight
universe: configs/universes/example_universe.yaml
schedule: configs/schedules/weekly_friday.yaml
cost_model: configs/costs/simple_cost.yaml

alpha_model:
  type: cross_sectional_momentum
  lookback_days: 126
  skip_recent_days: 5

risk_model:
  type: ewma_covariance
  halflife_days: 60

portfolio_construction:
  type: top_x_equal_weight
  x: 2
  constraints:
    max_weight: 0.60
    min_weight: 0.00
